graphviz==0.20.1
pip==22.0.4
pipdeptree==2.7.1
setuptools==56.0.0
streamlit==0.26.0
  - base58 [required: Any, installed: 2.1.1]
  - boto3 [required: Any, installed: 1.26.137]
    - botocore [required: >=1.29.137,<1.30.0, installed: 1.29.137]
      - jmespath [required: >=0.7.1,<2.0.0, installed: 1.0.1]
      - python-dateutil [required: >=2.1,<3.0.0, installed: 2.8.2]
        - six [required: >=1.5, installed: 1.16.0]
      - urllib3 [required: >=1.25.4,<1.27, installed: 1.26.15]
    - jmespath [required: >=0.7.1,<2.0.0, installed: 1.0.1]
    - s3transfer [required: >=0.6.0,<0.7.0, installed: 0.6.1]
      - botocore [required: >=1.12.36,<2.0a.0, installed: 1.29.137]
        - jmespath [required: >=0.7.1,<2.0.0, installed: 1.0.1]
        - python-dateutil [required: >=2.1,<3.0.0, installed: 2.8.2]
          - six [required: >=1.5, installed: 1.16.0]
        - urllib3 [required: >=1.25.4,<1.27, installed: 1.26.15]
  - botocore [required: Any, installed: 1.29.137]
    - jmespath [required: >=0.7.1,<2.0.0, installed: 1.0.1]
    - python-dateutil [required: >=2.1,<3.0.0, installed: 2.8.2]
      - six [required: >=1.5, installed: 1.16.0]
    - urllib3 [required: >=1.25.4,<1.27, installed: 1.26.15]
  - click [required: Any, installed: 8.1.3]
  - docutils [required: Any, installed: 0.20.1]
  - entrypoints [required: ==0.2.3, installed: 0.2.3]
  - enum-compat [required: Any, installed: 0.0.3]
  - future [required: Any, installed: 0.18.3]
  - future-fstrings [required: Any, installed: 1.2.0]
  - numpy [required: Any, installed: 1.24.3]
  - pandas [required: Any, installed: 2.0.1]
    - numpy [required: >=1.20.3, installed: 1.24.3]
    - python-dateutil [required: >=2.8.2, installed: 2.8.2]
      - six [required: >=1.5, installed: 1.16.0]
    - pytz [required: >=2020.1, installed: 2023.3]
    - tzdata [required: >=2022.1, installed: 2023.3]
  - pillow [required: !=5.1.0, installed: 9.5.0]
  - protobuf [required: Any, installed: 4.23.1]
  - psutil [required: Any, installed: 5.9.5]
  - toml [required: Any, installed: 0.10.2]
  - tornado [required: Any, installed: 6.3.2]
  - tzlocal [required: Any, installed: 5.0.1]
    - backports.zoneinfo [required: Any, installed: 0.2.1]
  - watchdog [required: Any, installed: 3.0.0]
