graphviz==0.20.1
pip==22.0.4
pipdeptree==2.7.1
requests==2.17.0
  - certifi [required: >=2017.4.17, installed: 2023.5.7]
  - chardet [required: >=3.0.2,<3.1.0, installed: 3.0.4]
  - idna [required: >=2.5,<2.6, installed: 2.5]
  - urllib3 [required: >=1.21.1,<1.22, installed: 1.21.1]
setuptools==56.0.0
