fastapi==0.65.1
  - pydantic [required: >=1.6.2,<2.0.0,!=1.8.1,!=1.8,!=1.7.3,!=1.7.2,!=1.7.1,!=1.7, installed: 1.10.7]
    - typing-extensions [required: >=4.2.0, installed: 4.5.0]
  - starlette [required: ==0.14.2, installed: 0.14.2]
graphviz==0.20.1
pip==22.0.4
pipdeptree==2.7.1
setuptools==56.0.0
