fastapi==0.52.0
  - pydantic [required: >=0.32.2,<2.0.0, installed: 1.10.7]
    - typing-extensions [required: >=4.2.0, installed: 4.5.0]
  - starlette [required: ==0.13.2, installed: 0.13.2]
graphviz==0.20.1
pip==22.0.4
pipdeptree==2.7.1
setuptools==56.0.0
