graphviz==0.20.1
pip==22.0.4
pipdeptree==2.7.1
setuptools==56.0.0
Sphinx==1.2.1
  - docutils [required: >=0.10, installed: 0.20.1]
  - Jinja2 [required: >=2.3, installed: 3.1.2]
    - MarkupSafe [required: >=2.0, installed: 2.1.2]
  - Pygments [required: >=1.2, installed: 2.15.1]
