graphviz==0.20.1
pip==22.0.4
pipdeptree==2.7.1
Sphinx==4.3.2
  - alabaster [required: >=0.7,<0.8, installed: 0.7.13]
  - babel [required: >=1.3, installed: 2.12.1]
    - pytz [required: >=2015.7, installed: 2023.3]
  - docutils [required: >=0.14,<0.18, installed: 0.17.1]
  - imagesize [required: Any, installed: 1.4.1]
  - Jinja2 [required: >=2.3, installed: 3.1.2]
    - MarkupSafe [required: >=2.0, installed: 2.1.2]
  - packaging [required: Any, installed: 23.1]
  - Pygments [required: >=2.0, installed: 2.15.1]
  - requests [required: >=2.5.0, installed: 2.30.0]
    - certifi [required: >=2017.4.17, installed: 2023.5.7]
    - charset-normalizer [required: >=2,<4, installed: 3.1.0]
    - idna [required: >=2.5,<4, installed: 3.4]
    - urllib3 [required: >=1.21.1,<3, installed: 2.0.2]
  - setuptools [required: Any, installed: 56.0.0]
  - snowballstemmer [required: >=1.1, installed: 2.2.0]
  - sphinxcontrib-applehelp [required: Any, installed: 1.0.4]
  - sphinxcontrib-devhelp [required: Any, installed: 1.0.2]
  - sphinxcontrib-htmlhelp [required: >=2.0.0, installed: 2.0.1]
  - sphinxcontrib-jsmath [required: Any, installed: 1.0.1]
  - sphinxcontrib-qthelp [required: Any, installed: 1.0.3]
  - sphinxcontrib-serializinghtml [required: >=1.1.5, installed: 1.1.5]
