graphviz==0.20.1
pandas==2.0.0rc1
  - numpy [required: >=1.20.3, installed: 1.24.3]
  - python-dateutil [required: >=2.8.2, installed: 2.8.2]
    - six [required: >=1.5, installed: 1.16.0]
  - pytz [required: >=2020.1, installed: 2023.3]
pip==22.0.4
pipdeptree==2.7.1
setuptools==56.0.0
